language: node_js
node_js: stable

# Travis-CI Caching
cache:
  directories:
    - node_modules


# S: Build Lifecycle
install:
  - npm install

before_script:
  - cp -r next/. themes/next 

script:
  - hexo g

after_script:
  - cd public
  - git init
  - git config user.name "HaviLee"
  - git config user.email "1058695900@qq.com"
  - git add .
  - git commit -m "Update docs:{{ now('YYYY-MM-DD HH:mm:ss') }} "
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/HaviLee/HaviLee.github.io.git
   - secure: "oLlSZ5WsnSgebfWgfGm1H3h7ODWWQ8amQTv6/zunouVuL1SP93iJMaJezFkQgUoKrjoNLrOZfjFjNXtylMckcZZlz/ws6SJrxG2qRhcMxY2uHe58fev6gj1ZU8AqGlfROfk9l5uRRTF7qz4fjEacpulhB+dm7Qjh9wskwrET2tnA/M49SEg90TlRUurfEBhffnW5CM4ZZRcJ0ItbOkVFWFiarCJj2o9TwGWdlDEV404P7tVlKXHZMl8h/OjFOCjvchGLtvicT+pZn97ws8muYU9CUZL8bebgmVxW0BXXfX8GLibUSyUmeBnQrH+hosU15377QjDDRlb1Eun8+clSCk+USfAGSM/lht42Wg6a1fVDAEd3ThF6qE0Mu0oQQa49etOMUU3l6FaN0W6eIuZXQ0Hx6vrtgf4NgO0Q/XPk5qKJaxCx/jX0qDMMAxtaE5tlLDMKJfPqsg9rkiAY0Y4AjhKWozXdnQ8tELC0JGYiZ+Itj1JFzzQD6yERW2GGfpEYIxjCRGuc9n/94+8py4NcKNf2RdaaE5TmViqGMJg37tuWHxu+pjEGEJYleMN/vNYUEYEEl75Z3XE+ttdskOjKYmFgnKqDJKi++7IQ52lwL6e5UhUNqJMkL5qOmTsg0mu9reSOO266Vq7Y06SebMbTC1LgqXHA9LthTJ3rEr4Us5c="
