language: node_js
node_js:
  - '6'
before_install:
- export TZ='Asia/Shanghai'  # 设置时区
- npm install -g hexo
- npm install -g hexo-cli

install:
  - npm install



before_script:
# 设置github账户信息
  - git config --global user.name "HaviLee" #设置github用户名
  - git config --global user.email 1058695900@qq.com #设置github用户邮箱
# github仓库操作
  - sed -i'' "s~${GH_REF}~${GH_TOKEN}:x-oauth-basic@${GH_REF}~" _config.yml
  - cd ./helloWorld


script:
  - hexo clean 
  - hexo g

after_success:
  - hexo deploy

branches:
  only:
    - develop
env:
 global:
   - GH_REF: github.com/HaviLee/HaviLee.github.io.git


# .travis.yml 配置this is new config
cache:
  directories:
    - node_modules
